spring.application.name=backend

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# MONGODB
# ===============================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ai_exam_db

# ===============================
# JWT
# ===============================
jwt.secret=ReplaceThisWithALongSecureSecretKeyAtLeast32CharactersLong
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=INFO

########################################
# MAIL CONFIGURATION
########################################

############################################
# MAIL CONFIGURATION (Temporary)
############################################

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test@test.com
spring.mail.password=test

########################################
# AI SERVICE
########################################

ai.service.url=http://localhost:8000